"""
SmartLogix Gateway — Green Mileage Certificate Generator (Task 7.6)

Generates a PDF certificate for each completed route, showing:
- Route details
- GLEC-framework carbon savings
- QR code with verification URL

Uses ReportLab for PDF generation per rules.md §2 ("swap for Python equivalents").
"""

import io
import logging
from datetime import datetime, timezone
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
)

from services.db import DBService, db_service

logger = logging.getLogger(__name__)


class CertificateService:
    """Generates green mileage PDF certificates."""

    def __init__(self, db: DBService | None = None):
        self._db = db or db_service

    async def generate_certificate(
        self, route_id: str, green_credit: dict[str, Any]
    ) -> bytes:
        """Generate a green mileage PDF certificate.

        Args:
            route_id: The completed route.
            green_credit: The green_credits record with computed savings.

        Returns:
            PDF bytes.
        """
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            topMargin=2 * cm,
            bottomMargin=2 * cm,
        )

        styles = getSampleStyleSheet()
        elements = []

        # Title
        title_style = styles["Title"]
        title_style.textColor = colors.HexColor("#0066ff")
        elements.append(Paragraph("Green Mileage Certificate", title_style))
        elements.append(Spacer(1, 10 * mm))

        # Subtitle
        elements.append(
            Paragraph(
                "SmartLogix — Dynamic Freight Consolidation & Green Routing",
                styles["Normal"],
            )
        )
        elements.append(Spacer(1, 10 * mm))

        # Certificate body
        elements.append(
            Paragraph(
                "This certifies that the following freight route achieved measurable "
                "carbon emission reductions through load consolidation, as computed "
                "under the GLEC Framework v3.0.",
                styles["Normal"],
            )
        )
        elements.append(Spacer(1, 8 * mm))

        # Data table
        data = [
            ["Route ID", route_id],
            [
                "Deadhead KM Saved",
                f'{green_credit.get("deadhead_km_saved", 0):.1f} km',
            ],
            [
                "Load Factor",
                f'{green_credit.get("load_factor", 0):.2f} tonnes',
            ],
            [
                "Emission Factor",
                f'{green_credit.get("emission_factor_used", 0.062)} kg CO₂e/tonne-km',
            ],
            [
                "CO₂e Saved",
                f'{green_credit.get("co2e_kg_saved", 0):.2f} kg',
            ],
            [
                "Date Issued",
                datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            ],
        ]

        table = Table(data, colWidths=[6 * cm, 10 * cm])
        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                    ("FONTSIZE", (0, 0), (-1, -1), 10),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("LEFTPADDING", (0, 0), (-1, -1), 10),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
                ]
            )
        )
        elements.append(table)
        elements.append(Spacer(1, 15 * mm))

        # Footer
        elements.append(
            Paragraph(
                "This certificate is auto-generated by the SmartLogix platform. "
                "Emission savings are computed using the GLEC Framework v3.0 "
                "formula: E = Σ(D_saved × W_freight × EF_diesel).",
                styles["Italic"],
            )
        )
        elements.append(Spacer(1, 5 * mm))
        elements.append(
            Paragraph(
                "Smart India Hackathon 2026 • SIH26198 • Team Alpha",
                styles["Normal"],
            )
        )

        doc.build(elements)
        pdf_bytes = buffer.getvalue()
        buffer.close()

        logger.info(
            f"Generated certificate for route {route_id}: {len(pdf_bytes)} bytes"
        )
        return pdf_bytes

    async def generate_and_store(
        self, route_id: str, green_credit: dict[str, Any]
    ) -> str | None:
        """Generate certificate PDF and upload to Supabase Storage.

        Returns:
            The storage path if successful, None on error.
        """
        try:
            pdf_bytes = await self.generate_certificate(route_id, green_credit)

            file_path = f"certificates/{route_id}/green-mileage.pdf"
            self._db.client.storage.from_("certificates").upload(
                file_path, pdf_bytes
            )

            logger.info(f"Certificate stored at {file_path}")
            return file_path

        except Exception as e:
            logger.error(f"Certificate generation failed for route {route_id}: {e}")
            return None


certificate_service = CertificateService()
